SELECT TOP 10 *
FROM dbo.customer;
--total number of revenue generated by gender
SELECT gender, SUM(purchase_amount) as Revenue
from dbo.customer
group by gender
--customers using discount and spending more than avg
SELECT customer_id, purchase_amount
from dbo.customer
where discount_applied='Yes' and purchase_amount>=(SELECT AVG(purchase_amount) from dbo.customer)
SELECT gender,
       AVG(purchase_amount) AS AvgPurchase
FROM dbo.customer
GROUP BY gender;
--top 5 products with highest review rating
SELECT top 5 item_purchased, ROUND(AVG(review_rating), 2) as "Average_Product_Rating"
FROM dbo.customer
group by item_purchased
order by AVG(review_rating) desc
--avg spend and total revenue between subscribers and non-subscriptions
SELECT subscription_status,COUNT(customer_id) as total_customers, ROUND(AVG(purchase_amount),2) AS avg_spend, ROUND(SUM(purchase_amount),2) as total_revenue
from dbo.customer
group by subscription_status
order by total_revenue, avg_spend desc
--5 products having highest % purchases with discount applied
SELECT TOP 5 item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM dbo.customer
group by item_purchased
order by discount_rate desc
--segment customers into new, returning and loyal baseed on their number of total purchases, and show the count of each segment
with customer_type as(
SELECT customer_id, previous_purchases,
CASE
WHEN previous_purchases=1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal' END AS customer_segment
FROM dbo.customer)
SELECT customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--3 most purchased products from each category
with item_counts as(
SELECT category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
FROM dbo.customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank<=3;
--repeat buyers' (more than 5 previous purchases) likelihood to subscribe
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM dbo.customer
WHERE previous_purchases>5
GROUP BY subscription_status
-- checking revenue by age group
SELECT age_group, SUM(purchase_amount) as total_revenue
FROM dbo.customer
GROUP BY age_group
ORDER by total_revenue DESC
--revenue by location
SELECT location,
       SUM(purchase_amount) AS Revenue
FROM dbo.customer
GROUP BY location
ORDER BY Revenue DESC;